// Copyright (c) 2026 CieloVista Software. All rights reserved.
// Unauthorized copying or distribution of this file is strictly prohibited.

// component: crv

/**
 * command-registry-viewer.ts
 *
 * Shows a searchable webview of all CVS command IDs cross-referenced with
 * the feature component that owns them.  Backed by data/commands-registry.json
 * which is generated by scripts/scan-commands.js.
 *
 * Commands:
 *   cvs.registry.showCommands  — open the Command Registry viewer
 *   cvs.registry.rebuild       — re-run scan-commands.js and refresh
 */

import * as vscode from 'vscode';
import * as path   from 'path';
import * as fs     from 'fs';
import { execFile } from 'child_process';
import { getChannel } from '../shared/output-channel';

const FEATURE   = 'command-registry-viewer';
const REGISTRY  = 'data/commands-registry.json';

let activePanel: vscode.WebviewPanel | undefined;

// ─── Activate ────────────────────────────────────────────────────────────────

export function activate(context: vscode.ExtensionContext): void {
    context.subscriptions.push(
        vscode.commands.registerCommand('cvs.registry.showCommands', () => showRegistry()),
        vscode.commands.registerCommand('cvs.registry.rebuild',      () => rebuildRegistry()),
    );
}

export function deactivate(): void {
    activePanel?.dispose();
}

// ─── Show ─────────────────────────────────────────────────────────────────────

function showRegistry(): void {
    if (activePanel) {
        activePanel.reveal();
        refreshPanel();
        return;
    }

    const panel = vscode.window.createWebviewPanel(
        'cvsCommandRegistry',
        'CVS Command Registry',
        vscode.ViewColumn.One,
        { enableScripts: true, retainContextWhenHidden: true }
    );
    activePanel = panel;
    panel.onDidDispose(() => { activePanel = undefined; });

    panel.webview.onDidReceiveMessage((msg: { type: string; url?: string; componentId?: string }) => {
        if (msg.type === 'rebuild') { void rebuildAndRefresh(panel); }
        if (msg.type === 'openFile' && msg.url) {
            const root = workspaceRoot();
            if (root) {
                const fp = path.join(root, msg.url);
                if (fs.existsSync(fp)) {
                    void vscode.workspace.openTextDocument(vscode.Uri.file(fp))
                        .then(doc => vscode.window.showTextDocument(doc, { preview: true }));
                }
            }
        }
    });

    refreshPanel();
}

function refreshPanel(): void {
    if (!activePanel) { return; }
    const registry = loadRegistry();
    activePanel.webview.html = buildHtml(registry);
}

// ─── Rebuild ─────────────────────────────────────────────────────────────────

function rebuildRegistry(): void {
    const root = workspaceRoot();
    if (!root) { void vscode.window.showWarningMessage('Open a workspace to rebuild the command registry.'); return; }
    void rebuildAndRefresh(activePanel);
}

async function rebuildAndRefresh(panel: vscode.WebviewPanel | undefined): Promise<void> {
    const root = workspaceRoot();
    if (!root) { return; }
    const ch = getChannel();
    ch.show(true);
    ch.appendLine('\n▶ Rebuilding command registry…');

    const scriptPath = path.join(root, 'scripts', 'scan-commands.js');
    if (!fs.existsSync(scriptPath)) {
        ch.appendLine('✗ scripts/scan-commands.js not found');
        return;
    }

    await new Promise<void>((resolve) => {
        execFile('node', [scriptPath], { cwd: root }, (err, stdout, stderr) => {
            if (stdout) { ch.appendLine(stdout.trimEnd()); }
            if (stderr) { ch.appendLine(stderr.trimEnd()); }
            ch.appendLine(err ? '✗ Rebuild failed' : '✓ Registry rebuilt');
            resolve();
        });
    });

    if (panel) {
        panel.webview.html = buildHtml(loadRegistry());
    }
}

// ─── Data ────────────────────────────────────────────────────────────────────

interface RegistryCommand {
    id:           string;
    title:        string;
    category:     string;
    description:  string;
    componentId:  string | null;
    featureTitle: string | null;
    featureFile:  string | null;
}

interface RegistryData {
    generated:        string;
    totalCommands:    number;
    linked:           number;
    unlinked:         number;
    totalComponents:  number;
    commands:         RegistryCommand[];
    unlinkedCommands: string[];
}

function workspaceRoot(): string | undefined {
    return vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
}

function loadRegistry(): RegistryData | null {
    const root = workspaceRoot();
    if (!root) { return null; }
    const fp = path.join(root, REGISTRY);
    if (!fs.existsSync(fp)) { return null; }
    try {
        return JSON.parse(fs.readFileSync(fp, 'utf8')) as RegistryData;
    } catch { return null; }
}

// ─── HTML ─────────────────────────────────────────────────────────────────────

function esc(s: string): string {
    return String(s ?? '')
        .replace(/&/g, '&amp;').replace(/</g, '&lt;')
        .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function buildHtml(registry: RegistryData | null): string {
    const css = `
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:var(--vscode-font-family);font-size:13px;color:var(--vscode-editor-foreground);background:var(--vscode-editor-background);min-height:100vh}
#hd{display:flex;align-items:center;justify-content:space-between;padding:12px 20px;background:var(--vscode-sideBar-background);border-bottom:1px solid var(--vscode-panel-border);position:sticky;top:0;z-index:10;gap:12px;flex-wrap:wrap}
h1{font-size:1.05em;font-weight:700}
.subtitle{font-size:11px;color:var(--vscode-descriptionForeground);margin-top:2px}
.btn{background:var(--vscode-button-secondaryBackground);color:var(--vscode-button-secondaryForeground);border:none;padding:6px 14px;border-radius:4px;cursor:pointer;font-size:12px;font-family:inherit}
.btn:hover{background:var(--vscode-button-secondaryHoverBackground)}
#body{padding:14px 20px}
.stats{display:flex;gap:20px;margin-bottom:12px;padding:10px 14px;background:var(--vscode-textCodeBlock-background);border-radius:4px;font-size:12px;flex-wrap:wrap}
.stat strong{font-size:18px;display:block;color:var(--vscode-textLink-foreground)}
.controls{display:flex;gap:8px;margin-bottom:12px;flex-wrap:wrap}
#search{flex:1;min-width:200px;background:var(--vscode-input-background);color:var(--vscode-input-foreground);border:1px solid var(--vscode-input-border,var(--vscode-panel-border));border-radius:4px;padding:7px 10px;font-size:12px;font-family:inherit}
#search:focus{outline:1px solid var(--vscode-focusBorder)}
#filter-linked{background:var(--vscode-input-background);color:var(--vscode-input-foreground);border:1px solid var(--vscode-input-border,var(--vscode-panel-border));border-radius:4px;padding:7px 8px;font-size:12px;font-family:inherit;cursor:pointer}
.table-wrap{border:1px solid var(--vscode-panel-border);border-radius:6px;overflow:auto;background:var(--vscode-textCodeBlock-background);max-height:calc(100vh - 230px)}
table{width:100%;border-collapse:collapse;min-width:900px}
thead th{position:sticky;top:0;background:var(--vscode-sideBar-background);z-index:2;border-bottom:1px solid var(--vscode-panel-border);text-align:left;padding:7px 10px;white-space:nowrap;font-size:12px}
tbody td{border-bottom:1px solid var(--vscode-panel-border);padding:7px 10px;vertical-align:top;font-size:12px}
tbody tr:hover{background:var(--vscode-list-hoverBackground)}
.cmd-id{font-family:var(--vscode-editor-font-family,monospace);font-size:11px;color:var(--vscode-textLink-foreground)}
.muted{color:var(--vscode-descriptionForeground);font-size:11px}
.tag{display:inline-block;padding:1px 6px;border-radius:10px;font-size:10px;font-weight:600}
.tag-linked{background:rgba(63,185,80,.14);color:#3fb950;border:1px solid rgba(63,185,80,.4)}
.tag-unlinked{background:rgba(248,81,73,.10);color:#f85149;border:1px solid rgba(248,81,73,.4)}
.file-btn{background:none;border:none;padding:0;color:var(--vscode-textLink-foreground);cursor:pointer;font:inherit;font-size:11px;text-decoration:underline;text-align:left}
.file-btn:hover{opacity:.8}
.empty{padding:40px;text-align:center;color:var(--vscode-descriptionForeground)}
`;

    if (!registry) {
        const body = `<div class="empty"><p style="font-size:15px;margin-bottom:10px">⚠ No command registry found</p><p>Run <strong>cvs.registry.rebuild</strong> or <code>node scripts/scan-commands.js</code> to generate <code>data/commands-registry.json</code>.</p></div>`;
        return wrapHtml(css, body);
    }

    const rows = registry.commands.map(cmd => {
        const linked = cmd.componentId !== null;
        const tag = linked
            ? `<span class="tag tag-linked">linked</span>`
            : `<span class="tag tag-unlinked">unlinked</span>`;
        const component = linked
            ? `${cmd.featureFile ? `<button class="file-btn" data-path="${esc(cmd.featureFile)}">${esc(cmd.featureTitle ?? cmd.componentId ?? '')}</button>` : esc(cmd.featureTitle ?? cmd.componentId ?? '')}`
            : `<span class="muted">—</span>`;
        return `<tr class="cmd-row" data-linked="${linked}" data-filter="${esc(cmd.id + ' ' + cmd.title + ' ' + cmd.category + ' ' + (cmd.componentId ?? '') + ' ' + (cmd.featureTitle ?? ''))}">
  <td><span class="cmd-id">${esc(cmd.id)}</span></td>
  <td>${esc(cmd.title)}</td>
  <td><span class="muted">${esc(cmd.category)}</span></td>
  <td>${tag}</td>
  <td>${component}</td>
  <td class="muted" style="font-size:11px">${esc(cmd.description).slice(0, 80)}${cmd.description.length > 80 ? '…' : ''}</td>
</tr>`;
    }).join('');

    const genAgo = registry.generated ? new Date(registry.generated).toLocaleString() : '?';
    const body = `
<div class="stats">
  <div class="stat"><strong>${registry.totalCommands}</strong>commands</div>
  <div class="stat"><strong>${registry.linked}</strong>linked</div>
  <div class="stat"><strong>${registry.unlinked}</strong>unlinked</div>
  <div class="stat"><strong>${registry.totalComponents}</strong>components</div>
</div>
<div class="controls">
  <input id="search" type="text" placeholder="Search by ID, title, category, component…">
  <select id="filter-linked">
    <option value="">all</option>
    <option value="true">linked only</option>
    <option value="false">unlinked only</option>
  </select>
  <button class="btn" id="rebuild-btn" type="button">⟳ Rebuild</button>
</div>
<div class="muted" style="margin-bottom:8px;font-size:11px">Generated: ${esc(genAgo)} — <span id="count-shown">${registry.totalCommands}</span> of ${registry.totalCommands} shown</div>
<div class="table-wrap"><table><thead><tr>
  <th>Command ID</th><th>Title</th><th>Category</th><th>Status</th><th>Component</th><th>Description</th>
</tr></thead><tbody id="rows">${rows}</tbody></table></div>`;

    const js = `(function(){
  var vsc = acquireVsCodeApi();
  var search = document.getElementById('search');
  var filterLinked = document.getElementById('filter-linked');
  var countShown = document.getElementById('count-shown');

  function applyFilter(){
    var q = (search.value || '').trim().toLowerCase();
    var lf = filterLinked.value;
    var shown = 0;
    document.querySelectorAll('.cmd-row').forEach(function(row){
      var txt = row.getAttribute('data-filter') || '';
      var linked = row.getAttribute('data-linked');
      var okQ = !q || txt.toLowerCase().includes(q);
      var okL = !lf || linked === lf;
      var ok = okQ && okL;
      row.style.display = ok ? '' : 'none';
      if (ok) shown++;
    });
    if (countShown) countShown.textContent = String(shown);
  }

  search.addEventListener('input', applyFilter);
  filterLinked.addEventListener('change', applyFilter);

  document.getElementById('rebuild-btn').addEventListener('click', function(){
    vsc.postMessage({ type: 'rebuild' });
  });

  document.querySelectorAll('.file-btn').forEach(function(btn){
    btn.addEventListener('click', function(){
      var p = btn.getAttribute('data-path');
      if (p) vsc.postMessage({ type: 'openFile', url: p });
    });
  });
})();`;

    return wrapHtml(css, body, js);
}

function wrapHtml(css: string, body: string, js?: string): string {
    return `<!DOCTYPE html><html lang="en"><head>
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none';style-src 'unsafe-inline';script-src 'unsafe-inline';">
<style>${css}</style>
</head><body>
<div id="hd">
  <div>
    <h1>📋 CVS Command Registry</h1>
    <div class="subtitle">Single source of truth — commands linked to feature components</div>
  </div>
</div>
<div id="body">${body}</div>
${js ? `<script>${js}</script>` : ''}
</body></html>`;
}
