/**
 * tests/install-verify.test.js
 * Verifies the CVT extension is correctly installed and its VSIX is valid.
 * Checks that required runtime modules are present in the installed extension.
 * Run: node tests/install-verify.test.js
 */

const cp   = require('child_process');
const fs   = require('fs');
const path = require('path');
const pkg  = JSON.parse(fs.readFileSync('./package.json', 'utf8'));

let pass = 0;
let fail = 0;

function ok(label, value, detail) {
    if (value) {
        console.log(`  PASS: ${label}${detail ? '\n         ' + detail : ''}`);
        pass++;
    } else {
        console.log(`  FAIL: ${label}${detail ? '\n         ' + detail : ''}`);
        fail++;
    }
}

function run(cmd) {
    try {
        return { out: cp.execSync(cmd, { encoding: 'utf8', stdio: ['ignore','pipe','pipe'] }).trim(), err: null };
    } catch (e) {
        return { out: (e.stdout || '').trim(), err: (e.stderr || e.message || '').trim() };
    }
}

console.log('\n-- CVT Install Verification --\n');

// 1. VSIX file exists
const vsix = `${pkg.name}-${pkg.version}.vsix`;
ok('VSIX file exists', fs.existsSync(vsix), vsix);

// 2. VSIX size is sane (> 100 KB, < 10 MB).
//    Upper bound covers: MCP SDK (~4.5 MB), diff, highlight.js, and compiled out/.
//    If we breach 10 MB, investigate — something's pulling in an unexpected tree.
if (fs.existsSync(vsix)) {
    const bytes = fs.statSync(vsix).size;
    const kb    = Math.round(bytes / 1024);
    ok('VSIX size is sane (100KB–10MB)', bytes > 100_000 && bytes < 10_000_000, `${kb} KB`);
}

// 3. Extension is installed — verified by checking the installed extension folder
//    on disk. `code-insiders --list-extensions` is unreliable during rebuild because
//    running VS Code Insiders caches its extension list and won't reflect fresh
//    copies from install.js until a reload. The disk folder is the source of
//    truth for what will load on next reload.
const extensionsRegistryPath = path.join(
    process.env.USERPROFILE || 'C:\\Users\\jwpmi',
    '.vscode-insiders', 'extensions',
    'extensions.json'
);

let extensionsRegistryParsed = null;
if (fs.existsSync(extensionsRegistryPath)) {
    try {
        extensionsRegistryParsed = JSON.parse(fs.readFileSync(extensionsRegistryPath, 'utf8').replace(/^\uFEFF/, ''));
        ok('Insiders extensions registry is valid JSON', true, extensionsRegistryPath);
    } catch (e) {
        ok('Insiders extensions registry is valid JSON', false, `${extensionsRegistryPath}\n         ${(e && e.message) ? e.message : String(e)}`);
    }

    if (extensionsRegistryParsed !== null) {
        ok('Insiders extensions registry has array shape', Array.isArray(extensionsRegistryParsed),
            Array.isArray(extensionsRegistryParsed) ? `${extensionsRegistryParsed.length} entries` : 'Top-level must be a JSON array');

        if (Array.isArray(extensionsRegistryParsed)) {
            const bad = extensionsRegistryParsed.filter((entry) =>
                !(entry && typeof entry === 'object' && entry.identifier && typeof entry.identifier.id === 'string' && entry.identifier.id.length > 0)
            );
            ok('Insiders extensions registry entries have identifier.id', bad.length === 0,
                bad.length === 0 ? 'OK' : `${bad.length} malformed entries`);
        }
    }
} else {
    ok('Insiders extensions registry exists or will be regenerated by VS Code', true, `Not found: ${extensionsRegistryPath}`);
}

const extId         = `${pkg.publisher.toLowerCase()}.${pkg.name}`;
const extFolder     = path.join(
    process.env.USERPROFILE || 'C:\\Users\\jwpmi',
    '.vscode-insiders', 'extensions',
    `${extId}-${pkg.version}`
);
const extPkgJson    = path.join(extFolder, 'package.json');
ok('Extension installed on disk (reload window to activate)',
    fs.existsSync(extPkgJson),
    fs.existsSync(extPkgJson) ? extFolder : `MISSING: ${extFolder}`);

// 4. package.json has required fields
ok('package.json: name',      !!pkg.name,      pkg.name);
ok('package.json: version',   !!pkg.version,   pkg.version);
ok('package.json: publisher', !!pkg.publisher, pkg.publisher);
ok('package.json: main',      !!pkg.main,      pkg.main);

// 5. Compiled output (main entry point) exists
const mainJs = pkg.main.replace(/^\.\//, '');
ok('Compiled main entry exists', fs.existsSync(mainJs), mainJs);

// 6. Extension bundle exists and is non-trivial (esbuild inlines all feature modules)
const bundleJs = 'out/extension.js';
const bundleSize = fs.existsSync(bundleJs) ? fs.statSync(bundleJs).size : 0;
ok('Extension bundle out/extension.js is non-trivial (>500KB)', bundleSize > 500_000,
    bundleSize > 0 ? `${Math.round(bundleSize / 1024)} KB` : 'MISSING');

// 7. Registry file is valid JSON with required shape
const REGISTRY_PATH = 'C:\\Users\\jwpmi\\Downloads\\CieloVistaStandards\\project-registry.json';
let registry = null;
try { registry = JSON.parse(fs.readFileSync(REGISTRY_PATH, 'utf8')); } catch { /* handled below */ }
ok('project-registry.json is valid JSON', !!registry, REGISTRY_PATH);
if (registry) {
    ok('Registry has globalDocsPath', typeof registry.globalDocsPath === 'string' && registry.globalDocsPath.length > 0, registry.globalDocsPath);
    ok('Registry has projects array',  Array.isArray(registry.projects), `${registry.projects?.length ?? 0} projects`);
    if (Array.isArray(registry.projects)) {
        for (const p of registry.projects) {
            ok(`Registry project "${p.name}" has path`, !!p.path, p.path);
        }
    }
}

// 8. install.js syntax valid
const check = run('node --check install.js');
ok('install.js syntax valid', check.err === null || check.err === '', check.err || 'OK');

// 8b. install.js regression guardrails (Windows path-with-spaces safe execution)
let installerSrc = '';
try { installerSrc = fs.readFileSync('install.js', 'utf8'); } catch { installerSrc = ''; }
ok('install.js readable', installerSrc.length > 0, installerSrc.length > 0 ? 'OK' : 'Could not read install.js');
if (installerSrc.length > 0) {
    ok('install.js uses spawnSync for CLI execution',
        installerSrc.includes('spawnSync('),
        installerSrc.includes('spawnSync(') ? 'OK' : 'Expected spawnSync(...) in runCli()');

    ok('install.js runCli disables shell parsing (shell:false)',
        /shell\s*:\s*false/.test(installerSrc),
        /shell\s*:\s*false/.test(installerSrc) ? 'OK' : 'Missing shell:false (required for Windows paths with spaces)');

    ok('install.js does not force shell:true in runCli',
        !/shell\s*:\s*true/.test(installerSrc),
        !/shell\s*:\s*true/.test(installerSrc) ? 'OK' : 'Found shell:true (can break command paths with spaces)');
}

// 9. CRITICAL: Installed extension folder has required files actually extracted.
//    Checks the INSTALLED location, not the project source folder.
//    A folder with only data/bg-health.json means the VSIX was never extracted.
const installedRoot = path.join(
    process.env.USERPROFILE || 'C:\\Users\\jwpmi',
    '.vscode-insiders', 'extensions',
    `${pkg.publisher.toLowerCase()}.${pkg.name}-${pkg.version}`
);
ok('Installed extension folder exists', fs.existsSync(installedRoot), installedRoot);

// These must exist IN THE INSTALLED FOLDER — not in the project source.
// If only data/bg-health.json is present, the VSIX was queued but never extracted.
const installedPkgJson = path.join(installedRoot, 'package.json');
const installedMainJs  = path.join(installedRoot, 'out', 'extension.js');
const pkgSize  = fs.existsSync(installedPkgJson) ? fs.statSync(installedPkgJson).size : 0;
const mainSize = fs.existsSync(installedMainJs)  ? fs.statSync(installedMainJs).size  : 0;
ok('Installed: package.json (>1KB)',           pkgSize  > 1000,    `${pkgSize} bytes — ${installedPkgJson}`);
ok('Installed: out/extension.js (>500KB)',     mainSize > 500_000, `${mainSize} bytes — ${installedMainJs}`);

if (fs.existsSync(installedRoot)) {
    // Scan compiled output for require() calls to non-builtin, non-vscode modules
    const builtins = new Set([
        'fs','path','os','child_process','crypto','http','https','net','stream',
        'util','events','url','buffer','assert','process','module','vm','zlib',
        'readline','node:fs','node:path','node:os','node:child_process','node:crypto',
        'node:http','node:https','node:net','node:stream','node:util','node:events',
        'node:url','node:buffer','node:assert','node:process','node:module',
        'node:vm','node:zlib','node:readline','node:worker_threads','worker_threads',
        'perf_hooks','node:perf_hooks','timers','node:timers',
    ]);

    const thirdPartyRequires = new Set();
    function scanJs(dir) {
        if (!fs.existsSync(dir)) { return; }
        for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
            if (e.name === 'node_modules') { continue; }
            const full = path.join(dir, e.name);
            if (e.isDirectory()) { scanJs(full); }
            else if (e.name.endsWith('.js')) {
                const src = fs.readFileSync(full, 'utf8');
                for (const m of src.matchAll(/require\(['"]([^./'][^'"]*)['"]\)/g)) {
                    const mod = m[1].startsWith('@')
                        ? m[1].split('/').slice(0, 2).join('/')
                        : m[1].split('/')[0];
                    if (mod !== 'vscode' && !builtins.has(mod)) {
                        thirdPartyRequires.add(mod);
                    }
                }
            }
        }
    }
    scanJs(path.join(installedRoot, 'out'));

    // Verify each third-party module is resolvable from the installed extension
    for (const mod of [...thirdPartyRequires].sort()) {
        const modPath = path.join(installedRoot, 'node_modules', mod.startsWith('@') ? mod : mod);
        const exists  = fs.existsSync(modPath);
        ok(`Runtime module resolvable: ${mod}`, exists, exists ? modPath : `MISSING — not in ${path.join(installedRoot, 'node_modules')}`);
    }

    const installedOutDir = path.join(installedRoot, 'out');
    if (!fs.existsSync(installedOutDir)) {
        ok('Installed out/ directory exists', false, `MISSING: ${installedOutDir} — VSIX was not extracted correctly`);
    } else if (thirdPartyRequires.size === 0) {
        ok('No third-party runtime requires found in compiled output', true, 'All requires are built-in or vscode');
    }
}

// ── Visual fix smoke tests ────────────────────────────────────────────────────
// Verifies that key visual and behavioral fixes are present in the compiled
// bundle. These catch regressions that the unit regression suite cannot see
// (CSS values, webview message handlers, UI strings).

const bundleSrc = fs.existsSync('out/extension.js') ? fs.readFileSync('out/extension.js', 'utf8') : '';

console.log('\n-- Visual Fix Smoke Tests --\n');

// #299 — README Compliance diff contrast (high-contrast red/green rows)
ok('#299 diff high-contrast deleted-line color (#3c1f1e) is in bundle',
    bundleSrc.includes('#3c1f1e'),
    'CSS .d2h-del background for deleted lines');
ok('#299 diff high-contrast inserted-line color (#1b3a24) is in bundle',
    bundleSrc.includes('#1b3a24'),
    'CSS .d2h-ins background for inserted lines');

// #300 — Approve & Write shows success toast and closes panel
ok('#300 Approve & Write emits success toast (Fix written)',
    bundleSrc.includes('Fix written'),
    'vscode.window.showInformationMessage after writing fix');
ok('#300 Approve & Write emits error toast on failure (Failed to write fix)',
    bundleSrc.includes('Failed to write fix'),
    'vscode.window.showErrorMessage on write failure');

// #296/#297 — Doc Catalog Rebuilt panel project rows open VS Code
ok('#297 Rebuilt panel rows have open-project-vscode action',
    bundleSrc.includes('open-project-vscode'),
    'data-action on project row + onDidReceiveMessage handler');

// #301 — README Compliance pill filters
ok('#301 Compliance pill filter-status action is in bundle',
    bundleSrc.includes('filter-status'),
    'data-action="filter-status" on pill buttons');
ok('#301 Compliance rows have data-status attribute',
    bundleSrc.includes('data-status'),
    'rows tagged with data-status for filter matching');

// #302 — Smart README fixer: frontmatter-aware heading insertion
// Function names are minified by esbuild — check source file and bundle strings instead.
const readmeFeatureSrc = (() => {
    const p = path.join(__dirname, '..', 'src', 'features', 'readme-compliance', 'feature.ts');
    try { return fs.readFileSync(p, 'utf8'); } catch { return ''; }
})();
ok('#302 Smart fixer frontmatterEnd helper exists in source',
    readmeFeatureSrc.includes('frontmatterEnd'),
    'src/features/readme-compliance/feature.ts must define frontmatterEnd()');
ok('#302 Smart fixer guessLanguage + LANG_HINTS exist in source',
    readmeFeatureSrc.includes('guessLanguage') && readmeFeatureSrc.includes('LANG_HINTS'),
    'src/features/readme-compliance/feature.ts must define guessLanguage() and LANG_HINTS');

// #304 — Zero docid collisions across registry (structural: REG-027 inline)
(function checkDocidCollisions() {
    const REGISTRY_PATH = 'C:\\Users\\jwpmi\\Downloads\\CieloVistaStandards\\project-registry.json';
    const SKIP_DIRS = new Set(['node_modules', '.git', 'bin', 'out', 'dist', '.vscode', '.vscode-test', '.claude', 'reports', 'CommandHelp', 'image-reader-assets']);
    let reg;
    try { reg = JSON.parse(fs.readFileSync(REGISTRY_PATH, 'utf8')); } catch { ok('#304 Zero docid collisions (registry loads)', false, 'Could not read registry'); return; }
    const docIdMap = new Map();
    function walkMd(dir, depth) {
        if (depth > 4 || !fs.existsSync(dir)) { return; }
        let entries; try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
        for (const e of entries) {
            if (SKIP_DIRS.has(e.name)) { continue; }
            const full = path.join(dir, e.name);
            if (e.isDirectory()) { walkMd(full, depth + 1); }
            else if (e.isFile() && /\.md$/i.test(e.name)) {
                let c; try { c = fs.readFileSync(full, 'utf8'); } catch { return; }
                const lines = c.split('\n');
                if (!lines[0] || lines[0].trim() !== '---') { return; }
                for (let i = 1; i < lines.length; i++) {
                    if (lines[i].trim() === '---') { break; }
                    const m = lines[i].trim().match(/^docid\s*:\s*(.+?)\s*$/i);
                    if (m) { const k = m[1].trim().toLowerCase(); if (!docIdMap.has(k)) { docIdMap.set(k, 0); } docIdMap.set(k, docIdMap.get(k) + 1); break; }
                }
            }
        }
    }
    for (const proj of reg.projects) { if (proj.path && fs.existsSync(proj.path)) { walkMd(proj.path, 0); } }
    const collisions = [...docIdMap.values()].filter(c => c > 1).length;
    ok(`#304 Zero docid collisions across registry (${docIdMap.size} docids scanned)`,
        collisions === 0,
        collisions === 0 ? 'All docids unique' : `${collisions} collision group(s) found — run scripts/fix-docid-collisions.js`);
})();

// #305 — README Compliance Copy button routes through vscode.env.clipboard (not navigator.clipboard)
ok('#305 README Compliance Copy button uses vscode.env.clipboard (not navigator.clipboard)',
    readmeFeatureSrc.includes('vscode.env.clipboard.writeText') &&
    readmeFeatureSrc.includes("case 'copy':"),
    'Extension host must handle copy command and write via vscode.env.clipboard');
ok('#305 README Compliance Copy button data-action is copy-row',
    readmeFeatureSrc.includes('data-action="copy-row"'),
    'Per-row Copy button must use data-action="copy-row"');
ok('#305 README Compliance AI Fix button removed',
    !readmeFeatureSrc.includes('btn-ai-row') && !readmeFeatureSrc.includes("action === 'ai-fix'"),
    'AI Fix button (btn-ai-row) must be gone from source');

// #307 — README Compliance Fix All: AI batch fix with per-file review
ok('#307 fixAllNonCompliant uses AI batch review (not blind write)',
    readmeFeatureSrc.includes('buildBatchReviewHtml') &&
    readmeFeatureSrc.includes("applyBatch") &&
    !readmeFeatureSrc.includes("'Write All'"),
    'Fix All must use AI batch review panel, not blind stub write');
ok('#307 fixAllNonCompliant confirmation says Run AI Fix',
    readmeFeatureSrc.includes("'Run AI Fix'"),
    'Confirmation dialog must say Run AI Fix so user understands AI is running');
ok('#307 batch review panel disposed on deactivate',
    readmeFeatureSrc.includes('_batchPanel') &&
    readmeFeatureSrc.includes('_batchPanel?.dispose()'),
    '_batchPanel must exist and be disposed in deactivate()');

// #313 — Doc Intelligence kind pills filter the findings list
ok('#313 Doc Intelligence kind pills are buttons with data-filter="kind:..."',
    bundleSrc.includes('data-filter="kind:'),
    'Kind pills must be <button> elements with data-filter="kind:<kind>" to enable click-filtering');
ok('#313 Doc Intelligence setFilter handles kind: prefix',
    bundleSrc.includes("startsWith('kind:')") || bundleSrc.includes('startsWith("kind:")'),
    'setFilter() must branch on kind: prefix to filter by finding type');
// Summary
console.log(`\n------------------------------------------------------------`);
console.log(`${pass + fail} checks: ${pass} passed, ${fail} failed`);
if (fail === 0) {
    console.log('\nCVT INSTALL VERIFIED -- all checks passed');
    process.exit(0);
} else {
    console.log('\nCVT INSTALL FAILED -- see above');
    process.exit(1);
}
