/**
 * launcher-script.test.js
 *
 * Tests the HTML/JS generated by buildLauncherHtml() by extracting
 * the <script> block and running it in a JSDOM-like environment via
 * Node's vm module. Validates that:
 *
 *  1. No reference to _activeTag (old single-tag variable)
 *  2. No reference to getElementById('chips') (old element removed)
 *  3. No reference to querySelectorAll('.chip') (old element removed)
 *  4. _activeTags Set is declared
 *  5. toggleDropdown function exists
 *  6. selectAllTopics function exists
 *  7. clearTopics function exists
 *  8. applyFilters uses _activeTags not _activeTag
 *  9. Run button handler uses vscode.postMessage
 * 10. clearAll calls clearTopics not chip manipulation
 */

const fs   = require('fs');
const path = require('path');

const srcPath = path.join(__dirname, '..', 'out', 'features', 'cvs-command-launcher.js');

// ── Check compiled output exists ─────────────────────────────────────────────
if (!fs.existsSync(srcPath)) {
    console.error('FAIL: compiled output not found at', srcPath);
    process.exit(1);
}

// ── Read the TS source directly (easier to grep) ──────────────────────────────
const tsSrc = fs.readFileSync(
    path.join(__dirname, '..', 'src', 'features', 'cvs-command-launcher.ts'),
    'utf8'
);

// Extract the script block (everything between <script> and </script> inside buildLauncherHtml)
const scriptMatch = tsSrc.match(/<script>\s*\(function\(\)[^]*?\}\)\(\);\s*<\/script>/);
if (!scriptMatch) {
    console.error('FAIL: Could not find IIFE script block in source');
    process.exit(1);
}
const scriptBlock = scriptMatch[0];

let passed = 0;
let failed = 0;

function test(name, fn) {
    try {
        fn();
        console.log('  PASS:', name);
        passed++;
    } catch (e) {
        console.error('  FAIL:', name, '-', e.message);
        failed++;
    }
}

function assert(condition, msg) {
    if (!condition) { throw new Error(msg); }
}

function assertNotContains(src, needle, msg) {
    assert(!src.includes(needle), msg || `Script must NOT contain: ${needle}`);
}

function assertContains(src, needle, msg) {
    assert(src.includes(needle), msg || `Script must contain: ${needle}`);
}

console.log('\nRunning CieloVista Launcher Script Tests...\n');

// ── 1. No stale _activeTag references ────────────────────────────────────────
test('No _activeTag variable (replaced by _activeTags Set)', () => {
    // Allow _activeTags but not _activeTag alone
    const matches = scriptBlock.match(/_activeTag[^s]/g) || [];
    assert(matches.length === 0, `Found ${matches.length} references to _activeTag (non-Set): ${matches.join(', ')}`);
});

// ── 2. No getElementById('chips') ─────────────────────────────────────────────
test('No getElementById("chips") — element was removed', () => {
    assertNotContains(scriptBlock, "getElementById('chips')");
    assertNotContains(scriptBlock, 'getElementById("chips")');
});

// ── 3. No querySelectorAll('.chip') ───────────────────────────────────────────
test('No querySelectorAll(".chip") — chip elements were removed', () => {
    assertNotContains(scriptBlock, "querySelectorAll('.chip')");
    assertNotContains(scriptBlock, 'querySelectorAll(".chip")');
});

// ── 4. _activeTags Set declared ───────────────────────────────────────────────
test('_activeTags declared as new Set()', () => {
    assertContains(scriptBlock, '_activeTags  = new Set()');
});

// ── 5. toggleDropdown exists ──────────────────────────────────────────────────
test('toggleDropdown handler attached to topic button', () => {
    assertContains(scriptBlock, "topicBtn.addEventListener('click'");
});

// ── 6. selectAllTopics function exists ────────────────────────────────────────
test('selectAllTopics function defined', () => {
    assertContains(scriptBlock, 'function selectAllTopics()');
});

// ── 7. clearTopics function exists ────────────────────────────────────────────
test('clearTopics function defined', () => {
    assertContains(scriptBlock, 'function clearTopics()');
});

// ── 8. applyFilters uses _activeTags not _activeTag ───────────────────────────
test('applyFilters uses _activeTags.size for topic matching', () => {
    assertContains(scriptBlock, '_activeTags.size');
});

// ── 9. Run button posts message via vscode.postMessage ───────────────────────
test('Run button calls vscode.postMessage with command:run', () => {
    assertContains(scriptBlock, "vscode.postMessage({ command: 'run', id: id })");
});

// ── 10. clearAll calls clearTopics ────────────────────────────────────────────
test('clearAll calls clearTopics() not chip manipulation', () => {
    assertContains(scriptBlock, 'clearTopics()');
    // Make sure clearAll doesn't do chip stuff
    const clearAllMatch = scriptBlock.match(/function clearAll\(\)[^}]+}/s);
    if (clearAllMatch) {
        assertNotContains(clearAllMatch[0], "querySelectorAll('.chip')");
    }
});

// ── 11. IIFE wrapper prevents global pollution ────────────────────────────────
test('Script wrapped in IIFE to prevent global scope pollution', () => {
    assertContains(scriptBlock, '(function() {');
    assertContains(scriptBlock, '\'use strict\';');
});

// ── 12. updateBadge function exists ───────────────────────────────────────────
test('updateBadge function defined', () => {
    assertContains(scriptBlock, 'function updateBadge()');
});

// ── 13. dd-select-all button wired up ─────────────────────────────────────────
test('dd-select-all button has event listener', () => {
    assertContains(scriptBlock, "getElementById('dd-select-all')");
});

// ── 14. dd-clear button wired up ──────────────────────────────────────────────
test('dd-clear button has event listener', () => {
    assertContains(scriptBlock, "getElementById('dd-clear')");
});

// ── 15. No filterGroup function calling _activeTag ────────────────────────────
test('Group bar handler does not reference old _activeTag', () => {
    const groupBarMatch = scriptBlock.match(/getElementById\('group-bar'\)[^}]+}/s);
    if (groupBarMatch) {
        assertNotContains(groupBarMatch[0], '_activeTag');
    }
});

// ── Summary ───────────────────────────────────────────────────────────────────
console.log(`\n${passed + failed} tests: ${passed} passed, ${failed} failed\n`);

if (failed > 0) {
    console.error('TESTS FAILED — buttons will be broken');
    process.exit(1);
} else {
    console.log('ALL TESTS PASSED — script is clean');
    process.exit(0);
}
