// Copyright (c) CieloVista Software. All rights reserved.
// REG-170: Issue #798 — the README Generator writes nothing the user has not
// reviewed, and never overwrites a README that appeared after the scan
//
// Run: node tests/regression/REG-170-readme-generator-writes-need-review.test.js
//
// #798: src/features/readme-generator.ts wrote AI output straight to disk from
// three places, with no diff and no approval:
//   - generateAllMissing()        "Generate All" (report button, cvs.readme.generate.run)
//   - generateSingleByName()      the per-project "Generate" button in the report
//   - generateSingleInteractive() cvs.readme.generate.single (quick pick)
// The first two work from the list of missing READMEs made at scan time, so a
// README.md created after the scan was overwritten without a check.
//
// All three now go through the shared review panel (src/shared/file-review.ts,
// moved there from README Compliance): one new-file diff per generated README,
// written only on approval, only the approved files, with the text the review
// showed. The generator never overwrites a README: existence is re-checked
// before the AI is called and again when it returns (a README that appeared
// after the scan is skipped and reported), and approval creates the file with
// 'wx', so one that appears while the review is open is not replaced either.
//
// #807: runScan() attached a new message listener to the reused report panel
// on every scan, so after N scans one click generated N times.
//
// This test runs the real handlers from out-test/ with vscode, the registry,
// the output channel and the AI mocked, over a temp set of projects:
//   Generate All (report button, warm scan cache)
//     1. After three scans, one click calls the AI once per project that is
//        still missing a README (#807), and writes nothing.
//     2. The review holds one new-file item per such project, carrying the AI
//        text; a README that appeared after the scan is skipped, not
//        generated, and the user is told.
//     3. Declining (closing the review, applying with nothing approved) writes
//        nothing.
//     4. Approving one writes exactly that file with the reviewed text; a path
//        the review was not given, or text it did not show, is never written.
//     5. A README that appears while the AI runs, or while the review is open
//        (even when approved: 'wx'), is never overwritten.
//   Generate one (report button)
//     6. Nothing is written before approval; approval writes the reviewed text.
//     7. A README that appeared after the scan is not generated or touched.
//   cvs.readme.generate.single (quick pick)
//     8. Nothing is written before approval; declining writes nothing;
//        approval writes the reviewed text; a README that appears before
//        Apply is not overwritten.

'use strict';

const fs     = require('fs');
const os     = require('os');
const path   = require('path');
const Module = require('module');

const ROOT = path.resolve(__dirname, '..', '..');
let passed = 0, failed = 0;
function check(name, ok, detail) {
    if (ok) { console.log(`  PASS ${name}`); passed++; }
    else    { console.error(`  FAIL ${name}${detail ? `\n       ${detail}` : ''}`); failed++; }
}

console.log('REG-170: README Generator writes need review (#798)');
console.log('-'.repeat(64));

const OUT = path.join(ROOT, 'out-test', 'features', 'readme-generator.js');
if (!fs.existsSync(OUT)) {
    check('out-test/features/readme-generator.js is built (the runner builds out-test/ every run)', false, OUT);
    finish();
}

// ── Temp projects ────────────────────────────────────────────────────────────
const TMP   = fs.mkdtempSync(path.join(os.tmpdir(), 'reg170-'));
const NAMES = ['alpha', 'beta', 'gamma'];
const DIR   = {};
const RM    = {};
for (const n of NAMES) {
    DIR[n] = path.join(TMP, n);
    fs.mkdirSync(DIR[n]);
    fs.writeFileSync(path.join(DIR[n], 'package.json'), JSON.stringify({ name: n, scripts: { build: 'tsc' } }), 'utf8');
    RM[n] = path.join(DIR[n], 'README.md');
}
const HAS_DIR   = path.join(TMP, 'has');
fs.mkdirSync(HAS_DIR);
const HAS_README = path.join(HAS_DIR, 'README.md');
const HAS_BEFORE = '# has\n\nAlready documented.\n';
fs.writeFileSync(HAS_README, HAS_BEFORE, 'utf8');
const BYSTANDER        = path.join(TMP, 'bystander.md');
const BYSTANDER_BEFORE = 'not part of any review\n';
const HAND = n => `# ${n}\n\nWritten by hand after the scan.\n`;

function resetFiles() {
    for (const n of NAMES) { try { fs.unlinkSync(RM[n]); } catch { /* absent */ } }
    fs.writeFileSync(HAS_README, HAS_BEFORE, 'utf8');
    fs.writeFileSync(BYSTANDER, BYSTANDER_BEFORE, 'utf8');
}

// ── Mocks ────────────────────────────────────────────────────────────────────
const aiText = n => `# ${n}\n\nGenerated by the mocked AI for ${n}.\n\n## Quick Start\n\n\`\`\`powershell\nnpm run build\n\`\`\`\n`;
const state = {};
function resetState(ui) { Object.assign(state, { ui: ui || {}, info: [], warnings: [], errors: [], aiCalls: [] }); }
resetState();
const panels   = [];
const handlers = {};
const vscodeMock = {
    ViewColumn: { One: 1, Beside: -2 },
    ProgressLocation: { Notification: 15 },
    Uri: { file: p => ({ fsPath: p }) },
    commands: {
        registerCommand(id, fn) { handlers[id] = fn; return { dispose() {} }; },
        async executeCommand() {},
    },
    workspace: {
        getConfiguration() { return { get() { return undefined; } }; },
        async openTextDocument(p) { return { fileName: p }; },
    },
    window: {
        showInformationMessage(msg) { state.info.push(msg); return Promise.resolve(undefined); },
        showErrorMessage(msg) { state.errors.push(msg); return Promise.resolve(undefined); },
        showWarningMessage(msg) { state.warnings.push(msg); return Promise.resolve(undefined); },
        async showQuickPick(items) { return state.ui.pick ? items.find(i => i.item.project.name === state.ui.pick) : undefined; },
        async withProgress(_opts, fn) { return fn({ report() {} }, { isCancellationRequested: false }); },
        async showTextDocument() {},
        createWebviewPanel(viewType, title) {
            const disposeFns = [];
            const panel = {
                viewType, title, html: '', listeners: [], disposed: false,
                webview: {
                    options: {},
                    set html(v) { panel.html = v; }, get html() { return panel.html; },
                    postMessage() { return Promise.resolve(true); },
                    onDidReceiveMessage(fn) {
                        panel.listeners.push(fn);
                        return { dispose() { panel.listeners = panel.listeners.filter(f => f !== fn); } };
                    },
                },
                reveal() {},
                onDidDispose(fn) { disposeFns.push(fn); return { dispose() {} }; },
                dispose() { if (panel.disposed) { return; } panel.disposed = true; disposeFns.forEach(f => f()); },
            };
            panels.push(panel);
            return panel;
        },
    },
};
const PROJECTS = [
    ...NAMES.map(n => ({ name: n, path: DIR[n], type: 'app', description: `${n} project` })),
    { name: 'has', path: HAS_DIR, type: 'app', description: 'has a README' },
];
const registryMock = {
    REGISTRY_PATH: path.join(TMP, 'project-registry.json'),
    loadRegistry: () => ({ globalDocsPath: TMP, projects: PROJECTS }),
};
const aiMock = {
    async callClaude(prompt) {
        const m = /Project name: (.*)/.exec(prompt);
        const name = m ? m[1].trim() : '?';
        state.aiCalls.push(name);
        const during = state.ui.createDuringAI;
        if (during === name) { fs.writeFileSync(RM[name], HAND(name), 'utf8'); }
        return aiText(name);
    },
};
const logMock = { log() {}, logError() {}, getChannel() { return { show() {}, appendLine() {} }; } };

const origLoad = Module._load;
Module._load = function (req, parent, isMain) {
    if (req === 'vscode') { return vscodeMock; }
    if (/[\\/]shared[\\/]registry$/.test(req))        { return registryMock; }
    if (/[\\/]shared[\\/]anthropic-client$/.test(req)) { return aiMock; }
    if (/[\\/]shared[\\/]output-channel$/.test(req))   { return logMock; }
    return origLoad.call(this, req, parent, isMain);
};
let feature;
try { feature = require(OUT); } finally { Module._load = origLoad; }
feature.activate({ subscriptions: [] });

const read   = p => fs.readFileSync(p, 'utf8');
const exists = p => fs.existsSync(p);
const livePanel = type => panels.filter(p => p.viewType === type && !p.disposed).pop();
const REVIEW = 'readmeGeneratorReview';
function reviewItems(panel) {
    const m = panel && panel.html.match(/const ITEMS = (\[[\s\S]*?\]);\n/);
    return m ? JSON.parse(m[1]) : [];
}
async function send(panel, msg) { for (const fn of [...panel.listeners]) { await fn(msg); } }
const noneWritten = () => !exists(RM.alpha) && !exists(RM.beta) && read(HAS_README) === HAS_BEFORE && read(BYSTANDER) === BYSTANDER_BEFORE;
const diskState   = () => NAMES.map(n => `${n}: ${exists(RM[n]) ? JSON.stringify(read(RM[n]).slice(0, 60)) : '(none)'}`).join(' | ');

(async () => {
    // ── Generate All, from the report's button with a warm scan cache ────────
    resetFiles(); resetState();
    await handlers['cvs.readme.generate.scan']();
    await handlers['cvs.readme.generate.scan']();
    await handlers['cvs.readme.generate.scan']();
    const report = livePanel('readmeGenerator');
    check('the README Generator report opens', !!report);
    if (!report) { return; }

    // gamma's README appears after the scan (by hand, git pull, New README...)
    fs.writeFileSync(RM.gamma, HAND('gamma'), 'utf8');

    async function generateAll() {
        resetState();
        await send(report, { command: 'generateAll' });
        return livePanel(REVIEW);
    }

    // 1 ── one click, one AI call per project, nothing written
    let review = await generateAll();
    check('one Generate All click calls the AI once per missing project, after three scans (#807)',
        state.aiCalls.length === 2 && ['alpha', 'beta'].every(n => state.aiCalls.includes(n)),
        JSON.stringify(state.aiCalls));
    check('the report panel has one message listener, not one per scan (#807)',
        report.listeners.length === 1, `${report.listeners.length} listeners`);
    check('a README that appeared after the scan is not generated (no AI call)',
        !state.aiCalls.includes('gamma'), JSON.stringify(state.aiCalls));
    check('Generate All writes nothing before approval',
        noneWritten() && read(RM.gamma) === HAND('gamma'), diskState());
    check('Generate All opens the review panel', !!review, `panels: ${panels.map(p => p.viewType).join(', ')}`);

    // 2 ── what the review holds
    let items = reviewItems(review);
    let byPath = new Map(items.map(i => [i.filePath, i]));
    check('the review holds one item per project still missing a README, and none for the one that appeared',
        items.length === 2 && byPath.has(RM.alpha) && byPath.has(RM.beta) && !byPath.has(RM.gamma),
        JSON.stringify(items.map(i => i.filePath)));
    const a1 = byPath.get(RM.alpha);
    check('a missing README is shown as a new file carrying the AI text',
        !!a1 && a1.aiContent === aiText('alpha') && /^--- .*\tnew file$/m.test(a1.unifiedDiff)
            && /^\+Generated by the mocked AI for alpha\.$/m.test(a1.unifiedDiff) && !/^-[^-]/m.test(a1.unifiedDiff),
        a1 ? a1.unifiedDiff.slice(0, 300) : 'no item for alpha');
    check('the user is told which README appeared after the scan and was not generated',
        state.warnings.some(m => /appeared after the scan/i.test(m) && m.includes('gamma')), state.warnings.join(' | '));
    check('the review offers Approve and Skip', !!review && /Approve/.test(review.html) && /Skip/.test(review.html));

    // 3 ── declining
    if (review) {
        review.dispose();
        check('closing the review without applying writes nothing', noneWritten() && read(RM.gamma) === HAND('gamma'), diskState());
        review = await generateAll();
        if (review) { await send(review, { command: 'applyBatch', approved: [] }); }
        check('applying with nothing approved writes nothing', noneWritten() && read(RM.gamma) === HAND('gamma'), diskState());
    }

    // 4 ── approving one: exactly that file, the reviewed text; forged paths ignored
    review = await generateAll();
    if (review) {
        await send(review, { command: 'applyBatch', approved: [
            { filePath: RM.alpha, content: 'FORGED' },
            { filePath: BYSTANDER, content: 'FORGED' },
            { filePath: RM.gamma, content: 'FORGED' },
        ] });
        check('approving one README writes it with the reviewed AI text, not the message\'s',
            exists(RM.alpha) && read(RM.alpha) === aiText('alpha'), diskState());
        check('the README that was not approved is not written', !exists(RM.beta), diskState());
        check('a path the review was not given is never written', read(BYSTANDER) === BYSTANDER_BEFORE, read(BYSTANDER));
        check('the README that appeared after the scan is untouched, even when the message names it', read(RM.gamma) === HAND('gamma'), diskState());
    } else {
        check('approving one README writes it with the reviewed AI text, not the message\'s', false, 'no review opened');
    }

    // 5 ── races: a README appears while the AI runs, or while the review is open
    resetFiles();
    await handlers['cvs.readme.generate.scan']();
    resetState({ createDuringAI: 'gamma' });
    await send(report, { command: 'generateAll' });
    review = livePanel(REVIEW);
    items = reviewItems(review);
    check('a README that appears while the AI runs is not put up for review',
        !items.some(i => i.filePath === RM.gamma) && read(RM.gamma) === HAND('gamma'), JSON.stringify(items.map(i => i.filePath)));
    if (review) {
        // after the review was built: beta's README appears
        fs.writeFileSync(RM.beta, HAND('beta'), 'utf8');
        await send(review, { command: 'applyBatch', approved: [
            { filePath: RM.alpha }, { filePath: RM.beta }, { filePath: RM.gamma },
        ] });
        check('a README that appears while the review is open is not overwritten, even when approved (wx)',
            read(RM.beta) === HAND('beta'), diskState());
        check('a README the review was not given is not overwritten, even when the message names it',
            read(RM.gamma) === HAND('gamma'), diskState());
        check('the other approved README is still written', exists(RM.alpha) && read(RM.alpha) === aiText('alpha'), diskState());
        check('the user is told which files were not written',
            [...state.info, ...state.warnings].some(m => /not written/.test(m) && m.includes(RM.beta)),
            [...state.info, ...state.warnings].join(' | '));
    } else {
        check('a README that appears while the review is open is not overwritten, even when approved (wx)', false, 'no review opened');
    }

    // ── Generate one, from the report's per-project button ───────────────────
    resetFiles(); resetState();
    await handlers['cvs.readme.generate.scan']();
    resetState();
    await send(report, { command: 'generateOne', project: 'alpha' });
    review = livePanel(REVIEW);
    items = reviewItems(review);
    check('Generate (one project) calls the AI once and writes nothing before approval',
        state.aiCalls.length === 1 && state.aiCalls[0] === 'alpha' && !exists(RM.alpha), `${JSON.stringify(state.aiCalls)} ${diskState()}`);
    check('Generate (one project) opens a review of that README as a new file',
        items.length === 1 && items[0].filePath === RM.alpha && items[0].aiContent === aiText('alpha') && /\tnew file$/m.test(items[0].unifiedDiff),
        JSON.stringify(items.map(i => i.filePath)));
    if (review) {
        await send(review, { command: 'applyBatch', approved: [{ filePath: RM.alpha, content: 'FORGED' }] });
        check('approving it writes the reviewed AI text', exists(RM.alpha) && read(RM.alpha) === aiText('alpha'), diskState());
    }

    // approving alpha rescanned; beta's README appears after that scan
    fs.writeFileSync(RM.beta, HAND('beta'), 'utf8');
    resetState();
    const reviewsBefore = panels.filter(p => p.viewType === REVIEW).length;
    await send(report, { command: 'generateOne', project: 'beta' });
    check('Generate (one project) on a README that appeared after the scan does not call the AI or overwrite it',
        state.aiCalls.length === 0 && read(RM.beta) === HAND('beta'), `${JSON.stringify(state.aiCalls)} ${diskState()}`);
    check('it opens no review and tells the user the README exists',
        panels.filter(p => p.viewType === REVIEW).length === reviewsBefore && !livePanel(REVIEW)
            && state.warnings.some(m => /appeared after the scan/i.test(m) && m.includes('beta')),
        state.warnings.join(' | '));

    // ── cvs.readme.generate.single (quick pick) ──────────────────────────────
    resetFiles();
    resetState({ pick: 'gamma' });
    await handlers['cvs.readme.generate.single']();
    review = livePanel(REVIEW);
    items = reviewItems(review);
    check('Generate Single calls the AI for the picked project and writes nothing before approval',
        state.aiCalls.length === 1 && state.aiCalls[0] === 'gamma' && !exists(RM.gamma), `${JSON.stringify(state.aiCalls)} ${diskState()}`);
    check('Generate Single opens a review of the generated README as a new file',
        items.length === 1 && items[0].filePath === RM.gamma && items[0].aiContent === aiText('gamma') && /\tnew file$/m.test(items[0].unifiedDiff),
        JSON.stringify(items.map(i => i.filePath)));
    if (review) {
        await send(review, { command: 'applyBatch', approved: [] });
        check('Generate Single: applying with nothing approved writes nothing', !exists(RM.gamma), diskState());
    }

    resetState({ pick: 'gamma' });
    await handlers['cvs.readme.generate.single']();
    review = livePanel(REVIEW);
    if (review) {
        await send(review, { command: 'applyBatch', approved: [{ filePath: RM.gamma }] });
        check('Generate Single: approving writes the reviewed AI text', exists(RM.gamma) && read(RM.gamma) === aiText('gamma'), diskState());
    }

    try { fs.unlinkSync(RM.gamma); } catch { /* absent */ }
    resetState({ pick: 'gamma' });
    await handlers['cvs.readme.generate.single']();
    review = livePanel(REVIEW);
    if (review) {
        fs.writeFileSync(RM.gamma, HAND('gamma'), 'utf8');
        await send(review, { command: 'applyBatch', approved: [{ filePath: RM.gamma }] });
        check('Generate Single: a README that appears before Apply is not overwritten', read(RM.gamma) === HAND('gamma'), diskState());
    } else {
        check('Generate Single: a README that appears before Apply is not overwritten', false, 'no review opened');
    }

    resetFiles();
    resetState({ pick: 'alpha' });
    await handlers['cvs.readme.generate.single']();
    const open = livePanel(REVIEW);
    feature.deactivate();
    check('deactivate closes an open review panel and writes nothing', !!open && open.disposed && !exists(RM.alpha), diskState());
    check('the project that already had a README was never touched', read(HAS_README) === HAS_BEFORE);
})().catch(err => check('the handlers ran', false, err && err.stack || String(err)))
    .finally(() => { try { fs.rmSync(TMP, { recursive: true, force: true }); } catch { /* temp dir */ } finish(); });

function finish() {
    console.log('-'.repeat(64));
    console.log(`${passed} passed, ${failed} failed`);
    process.exit(failed ? 1 : 0);
}
