/**
 * REG-157-feature-catalogue-lists-folder-features.test.js
 *
 * Guards #755. docs/using/features.md is the user-facing feature catalogue,
 * generated by scripts/docs-sync.js between docs-sync markers. It built its
 * list from flat src/features/*.ts files only, so every folder feature
 * (src/features/<name>/index.ts + README.md) was left out: doc-catalog,
 * doc-header, mcp-viewer, github-issues and seven more. It also listed three
 * flat modules that nothing activates.
 *
 * The rule: a feature is a top-level module under src/features/ that
 * src/extension.ts imports. extension.ts is wiring only, so its import list is
 * the list of features that actually run. This test derives that list on its
 * own, from extension.ts, and does not reuse the script's code.
 *
 * It asserts:
 *   1. the extension.ts import parser finds the features (a sanity floor, and
 *      the known folder features doc-catalog, doc-header, mcp-viewer,
 *      github-issues and readme-compliance are among them), so the checks
 *      below cannot pass by parsing nothing
 *   2. every feature extension.ts imports, file or folder, has exactly one
 *      line in the generated catalogue
 *   3. that line links to the feature's own README (src/features/<id>/README.md
 *      for a folder feature, src/features/<id>.README.md for a file feature),
 *      and the link resolves to a file that exists
 *   4. readme-compliance, which has both readme-compliance.ts and
 *      readme-compliance/, is listed once, pointing at the folder extension.ts
 *      imports
 *   5. every link in the generated block resolves, and none lists a module
 *      extension.ts does not import (config-editor, playwright-check and
 *      script-runner are not wired, so they are not features)
 *   6. each entry uses the README's own title, not a bare id
 *   7. node scripts/docs-sync.js --check passes: the committed catalogue is
 *      exactly what the generator produces
 *   8. --check FAILS, naming the feature, when a folder feature's line is
 *      removed from the catalogue (run on a scratch copy of the repo)
 *
 * Read-only against the repo: check 8 works on a copy under the OS temp dir.
 *
 * Run: node tests/regression/REG-157-feature-catalogue-lists-folder-features.test.js
 */
'use strict';

const fs   = require('fs');
const os   = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const ROOT      = path.resolve(__dirname, '..', '..');
const FEATURES  = path.join(ROOT, 'src', 'features');
const EXTENSION = path.join(ROOT, 'src', 'extension.ts');
const CATALOGUE = path.join(ROOT, 'docs', 'using', 'features.md');
const SYNC      = path.join(ROOT, 'scripts', 'docs-sync.js');

const BEGIN = '<!-- docs-sync:begin -->';
const END   = '<!-- docs-sync:end -->';

const KNOWN_FOLDER_FEATURES = ['doc-catalog', 'doc-header', 'mcp-viewer', 'github-issues', 'readme-compliance'];
const NOT_WIRED             = ['config-editor', 'playwright-check', 'script-runner'];

let passed = 0, failed = 0;
function test(name, fn) {
    try { fn(); passed++; console.log(`  ✓ ${name}`); }
    catch (err) { failed++; console.error(`  ✗ ${name}\n      → ${err && err.message}`); }
}
function assert(cond, msg) { if (!cond) { throw new Error(msg); } }

/** { id -> 'folder' | 'file' } for every ./features/ import in extension.ts. */
function wiredFeatures() {
    const src = fs.readFileSync(EXTENSION, 'utf8')
        .replace(/\/\*[\s\S]*?\*\//g, '')
        .replace(/^\s*\/\/.*$/gm, '');
    const out = new Map();
    for (const m of src.matchAll(/from\s+'\.\/features\/([^']+)'/g)) {
        const spec = m[1];
        const id   = spec.split('/')[0];
        const folder = spec.includes('/') || !fs.existsSync(path.join(FEATURES, `${id}.ts`));
        if (folder || !out.has(id)) { out.set(id, folder ? 'folder' : 'file'); }
    }
    return out;
}

/** The generated block's entries: [{ title, href, resolved }]. */
function catalogueEntries(text) {
    const start = text.indexOf(BEGIN);
    const end   = text.indexOf(END);
    assert(start >= 0 && end > start, 'docs/using/features.md has no docs-sync block');
    const block = text.slice(start + BEGIN.length, end);
    const entries = [];
    for (const line of block.split(/\r?\n/)) {
        const m = line.match(/^- \[([^\]]+)\]\(([^)\s]+)\)/);
        if (!m) { continue; }
        entries.push({
            title:    m[1],
            href:     m[2],
            resolved: path.resolve(path.dirname(CATALOGUE), m[2]),
        });
    }
    return entries;
}

/** Which feature id a README path documents, or null. */
function idForReadme(abs) {
    const rel = path.relative(FEATURES, abs).split(path.sep).join('/');
    let m = rel.match(/^([^/]+)\/README\.md$/);
    if (m) { return { id: m[1], kind: 'folder' }; }
    m = rel.match(/^([^/]+)\.README\.md$/);
    if (m) { return { id: m[1], kind: 'file' }; }
    return null;
}

function readmeTitle(abs) {
    const text = fs.readFileSync(abs, 'utf8');
    const top  = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    const t    = top && top[1].match(/^title:\s*(.+)$/m);
    const raw  = t ? t[1].trim().replace(/^["']|["']$/g, '') : (text.match(/^#\s+(.+)$/m) || [])[1] || '';
    return raw.replace(/^Feature:\s*/i, '').trim();
}

console.log('\nREG-157: the feature catalogue lists every activated feature, file or folder (#755)\n' + '-'.repeat(72));

const wired   = wiredFeatures();
const entries = catalogueEntries(fs.readFileSync(CATALOGUE, 'utf8'));
const byId    = new Map();
for (const e of entries) {
    const owner = idForReadme(e.resolved);
    if (!owner) { continue; }
    if (!byId.has(owner.id)) { byId.set(owner.id, []); }
    byId.get(owner.id).push({ ...e, kind: owner.kind });
}

const folderCount = [...wired.values()].filter(k => k === 'folder').length;
console.log(`  (extension.ts imports ${wired.size} features: ${wired.size - folderCount} file, ${folderCount} folder; catalogue has ${entries.length} entries)`);

test('1. the extension.ts parser finds the features, including the known folder features', () => {
    assert(wired.size >= 50, `only ${wired.size} feature imports found in src/extension.ts`);
    const missing = KNOWN_FOLDER_FEATURES.filter(id => wired.get(id) !== 'folder');
    assert(!missing.length, `not seen as folder features: ${missing.join(', ')}`);
});

test('2. every feature extension.ts imports has exactly one catalogue line', () => {
    const absent = [...wired.keys()].filter(id => !byId.has(id));
    const dupes  = [...byId.entries()].filter(([, list]) => list.length > 1).map(([id]) => id);
    assert(!absent.length, `${absent.length} activated feature(s) missing from the catalogue: ${absent.join(', ')}`);
    assert(!dupes.length, `listed more than once: ${dupes.join(', ')}`);
});

test('3. each line links to that feature\'s own README, and the link resolves', () => {
    const bad = [];
    for (const [id, kind] of wired) {
        const list = byId.get(id) || [];
        const hit  = list.find(e => e.kind === kind && fs.existsSync(e.resolved))
            // A file feature without a flat README may fall back to a folder one, and vice versa.
            || list.find(e => fs.existsSync(e.resolved));
        if (!hit) { bad.push(`${id} (${kind})`); continue; }
        const own = kind === 'folder'
            ? path.join(FEATURES, id, 'README.md')
            : path.join(FEATURES, `${id}.README.md`);
        if (fs.existsSync(own) && path.resolve(hit.resolved) !== path.resolve(own)) {
            bad.push(`${id}: links ${hit.href}, expected its ${kind} README`);
        }
    }
    assert(!bad.length, `no resolving link to the feature's README: ${bad.join('; ')}`);
});

test('4. readme-compliance (both .ts and folder) is listed once, at the folder it is imported from', () => {
    assert(fs.existsSync(path.join(FEATURES, 'readme-compliance.ts')), 'fixture changed: readme-compliance.ts is gone');
    assert(fs.existsSync(path.join(FEATURES, 'readme-compliance', 'index.ts')), 'fixture changed: readme-compliance/ is gone');
    const list = byId.get('readme-compliance') || [];
    const all  = entries.filter(e => /src\/features\/readme-compliance[./]/.test(e.href));
    assert(all.length === 1, `readme-compliance appears ${all.length} times`);
    assert(list.length === 1 && list[0].kind === 'folder',
        `readme-compliance links ${all.map(e => e.href).join(', ')}, expected ../../src/features/readme-compliance/README.md`);
});

test('5. every link resolves, and nothing unwired is listed as a feature', () => {
    const broken  = entries.filter(e => !fs.existsSync(e.resolved)).map(e => e.href);
    const unwired = entries.map(e => idForReadme(e.resolved)).filter(o => !o || !wired.has(o.id));
    assert(!broken.length, `links that do not resolve: ${broken.join(', ')}`);
    assert(!unwired.length, `listed but not imported by extension.ts: ${unwired.map(o => o ? o.id : '?').join(', ')}`);
    const stillListed = NOT_WIRED.filter(id => entries.some(e => e.href.includes(`/${id}.README.md`)));
    assert(!stillListed.length, `not activated anywhere, yet listed: ${stillListed.join(', ')}`);
});

test('6. each entry uses its README\'s own title', () => {
    const wrong = [];
    for (const e of entries) {
        const want = readmeTitle(e.resolved);
        if (want && e.title !== want) { wrong.push(`${e.href}: "${e.title}" != "${want}"`); }
    }
    assert(!wrong.length, wrong.join('; '));
});

test('7. docs-sync --check passes: the committed catalogue is what the generator writes', () => {
    const r = spawnSync(process.execPath, [SYNC, '--check'], { cwd: ROOT, encoding: 'utf8' });
    assert(r.status === 0, `docs-sync --check exited ${r.status}:\n${(r.stdout || '') + (r.stderr || '')}`);
});

test('8. docs-sync --check fails, naming it, when a folder feature is missing from the catalogue', () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'reg157-'));
    try {
        for (const dir of ['src', 'docs', 'scripts']) {
            fs.cpSync(path.join(ROOT, dir), path.join(tmp, dir), { recursive: true });
        }
        const copy = path.join(tmp, 'docs', 'using', 'features.md');
        const text = fs.readFileSync(copy, 'utf8');
        const cut  = text.split('\n').filter(l => !l.includes('src/features/doc-header/README.md')).join('\n');
        assert(cut !== text, 'fixture: the catalogue has no doc-header/README.md line to remove');
        fs.writeFileSync(copy, cut);
        const r   = spawnSync(process.execPath, [path.join(tmp, 'scripts', 'docs-sync.js'), '--check'],
            { cwd: tmp, encoding: 'utf8' });
        const out = (r.stdout || '') + (r.stderr || '');
        assert(r.status !== 0, 'docs-sync --check passed with doc-header removed from the catalogue');
        assert(/not in the catalogue[^\n]*(?:— |, )doc-header(?:,|\s*$)/m.test(out),
            `--check failed but did not name doc-header as missing:\n${out}`);
    } finally {
        fs.rmSync(tmp, { recursive: true, force: true });
    }
});

console.log('-'.repeat(72));
console.log(`  ${passed} passed, ${failed} failed\n`);
process.exit(failed ? 1 : 0);
